# Generated by Django 5.1.1 on 2024-10-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_message_delete_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(max_length=300),
        ),
    ]
