# Generated by Django 5.1.2 on 2024-10-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pre_order_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
