# Generated by Django 5.1.1 on 2024-10-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_remove_product_images_product_image1_product_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, default='No Brand', max_length=50, null=True),
        ),
    ]
