# Generated by Django 5.1.2 on 2024-10-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_product_pre_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pre_order_available',
            field=models.BooleanField(default=True),
        ),
    ]
