# Generated by Django 5.1.2 on 2024-10-26 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_alter_product_brand'),
    ]

    operations = [
    ]
