version: '3.8'

services:
  db:
    image: postgres:17
    env_file:
      - SilverShop/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6

  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 SilverShop.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - SilverShop/.env

  celery:
    build: .
    command: celery -A SilverShop worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - SilverShop/.env

  celery-beat:
    build: .
    command: celery -A SilverShop beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - SilverShop/.env

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  
      PGADMIN_DEFAULT_PASSWORD: admin  
    depends_on:
      - db
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
