# Generated by Django 5.1.2 on 2024-11-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preorderqueue',
            name='reservation_status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('reserved', 'Reserved'), ('expired', 'Expired'), ('fully_paid', 'Fully Paid')], default='waiting', max_length=20),
        ),
    ]
