# Generated by Django 5.1.1 on 2024-10-15 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0003_wishlist_wishlistitem'),
        ('product_app', '0004_alter_product_brand'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('wishlist', 'product')},
        ),
    ]
