# Generated by Django 5.1.2 on 2024-10-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0005_cartitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_preordered',
            field=models.BooleanField(default=False),
        ),
    ]
