# Generated by Django 5.1.2 on 2024-10-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_compeleted',
            field=models.BooleanField(default=False),
        ),
    ]
