# Generated by Django 5.1.2 on 2024-10-27 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_user_is_compeleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_compeleted',
            new_name='is_completed',
        ),
    ]
