# Generated by Django 5.1.2 on 2024-10-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_rename_is_compeleted_user_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_spent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
