# Generated by Django 5.1.2 on 2024-10-26 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_remove_user_password_remove_user_username_and_more'),
    ]

    operations = [
    ]
