# Generated by Django 5.1.2 on 2024-10-26 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_populate_phone_number'),
    ]

    operations = [
    ]
